x86, init: Default IRQ_WORK to 'on'
Turning off perf, we get the following link error because IRQ_WORK
gets turned off.  Keep it on by default.

| arch/x86/built-in.o: In function `do_machine_check':
| (.text+0xaf0e): undefined reference to `irq_work_queue'

Signed-off-by: Tom Zanussi <tom.zanussi@linux.intel.com>